
      // Массив слов
      const words = [
        { word: "взрослый", translation: "adult" }, 
        { word: "возраст", translation: "age" }, 
        { word: "малыш", translation: "baby" }, 
        { word: "рождение", translation: "birth" }, 
        { word: "мальчик", translation: "boy" }, 
        { word: "ребенок", translation: "child" }, 
        { word: "детство", translation: "childhood" }, 
        { word: "девочка", translation: "girl" }, 
        { word: "человек", translation: "person" }, 
        { word: "ребенок", translation: "child" }, 
        { word: "жизнь", translation: "life" }, 
        { word: "девичья фамилия", translation: "maiden name" }, 
        { word: "мужчина", translation: "man" }, 
        { word: "имя", translation: "name" }, 
        { word: "люди", translation: "people" }, 
        { word: "человек", translation: "person" }, 
        { word: "личность", translation: "personality" }, 
        { word: "фамилия", translation: "surname" }, 
        { word: "подросток", translation: "teenager" },
        { word: "женщина", translation: "woman" },
        { word: "молодежь", translation: "youth" }, 
        { word: "молодость", translation: "youth" }, 
        { word: "рука", translation: "hand" }, 
        { word: "спина", translation: "back" }, 
        { word: "живот", translation: "belly" }, 
        { word: "кровь", translation: "blood" }, 
        { word: "тело", translation: "body" }, 
        { word: "кость", translation: "bone" },
        { word: "мозг", translation: "brain" },
        { word: "щека", translation: "cheek" }, 
        { word: "грудь", translation: "chest" }, 
        { word: "подбородок", translation: "chin" }, 
        { word: "ухо", translation: "ear" }, 
        { word: "локоть", translation: "elbow" }, 
        { word: "глаз", translation: "eye" }, 
        { word: "бровь", translation: "eyebrow" }, 
        { word: "ресница", translation: "eyelash" }, 
        { word: "лицо", translation: "face" }, 
        { word: "палец", translation: "finger" }, 
        { word: "кулак", translation: "fist" }, 
        { word: "ступня", translation: "foot" }, 
        { word: "лоб", translation: "forehead" }, 
        { word: "волосы", translation: "hair" }, 
        { word: "кисть руки", translation: "hand" }, 
        { word: "сердце", translation: "heart" }, 
        { word: "пятка", translation: "heel" }, 
        { word: "бедро", translation: "hip" }, 
        { word: "челюсть", translation: "jaw" }, 
        { word: "почка", translation: "kidney" }, 
        { word: "колено", translation: "knee" }, 
        { word: "нога", translation: "leg" }, 
        { word: "губы", translation: "lips" }, 
        { word: "мизинец", translation: "little finger" },
        { word: "печень", translation: "liver" },
        { word: "легкое", translation: "lung" }, 
    { word: "рот", translation: "mouth" }, 
    { word: "мышца", translation: "muscle" }, 
    { word: "ноготь", translation: "nail" }, 
    { word: "шея", translation: "neck" }, 
    { word: "нерв", translation: "nerve" }, 
    { word: "нос", translation: "nose" }, 
    { word: "ладонь", translation: "palm" },
    { word: "ребро", translation: "rib" }, 
    { word: "безымянный палец", translation: "ring finger" }, 
    { word: "скелет", translation: "skeleton" }, 
    { word: "кожа", translation: "skin" }, 
    { word: "череп", translation: "skull" }, 
    { word: "желудок", translation: "stomach" }, 
    { word: "горло", translation: "throat" },
    { word: "большой палец", translation: "thumb" }, 
    { word: "палец на ноге", translation: "toe" }, 
    { word: "язык", translation: "tongue" },
    { word: "зуб", translation: "tooth" }, 
    { word: "запястье", translation: "wrist" }, 
    { word: "привлекательный", translation: "attractive" }, 
    { word: "лысый", translation: "bald" }, 
    { word: "борода", translation: "beard" }, 
    { word: "красивый", translation: "beautiful" }, 
    { word: "красота", translation: "beauty" }, 
    { word: "белокурый", translation: "blond" }, 
    { word: "густой", translation: "thick" }, 
    { word: "обычный", translation: "ordinary" }, 
    { word: "кудрявый", translation: "curly" }, 
    { word: "милый", translation: "cute" }, 
    { word: "темный", translation: "dark" }, 
    { word: "белокурый", translation: "blond" }, 
    { word: "толстый", translation: "fat" }, 
    { word: "фигура", translation: "figure" }, 
    { word: "румянец", translation: "blush" }, 
    { word: "веснушки", translation: "freckles" }, 
    { word: "рыжий", translation: "red-haired" }, 
    { word: "прическа", translation: "hairstyle" }, 
    { word: "рост", translation: "height" }, 
    { word: "крючковатый", translation: "hooked" }, 
    { word: "усы", translation: "mustache" }, 
    { word: "овальный", translation: "oval" }, 
    { word: "бледный", translation: "pale" }, 
    { word: "пухлый", translation: "plump" }, 
    { word: "круглый", translation: "round" }, 
    { word: "короткий", translation: "short" }, 
    { word: "тонкий", translation: "thin" }, 
    { word: "квадратный", translation: "square" }, 
    { word: "прямой", translation: "straight" },
    { word: "высокий", translation: "tall" }, 
    { word: "худой", translation: "skinny" }, 
    { word: "уродливый", translation: "ugly" }, 
    { word: "волнистый", translation: "wavy" }, 
    { word: "вес", translation: "weight" },
    { word: "активный", translation: "active" }, 
    { word: "злой", translation: "angry" }, 
    { word: "грустный", translation: "sad" }, 
    { word: "скучный", translation: "boring" }, 
    { word: "храбрый", translation: "brave" }, 
    { word: "спокойный", translation: "calm" }, 
    { word: "осторожный", translation: "careful" }, 
    { word: "характер", translation: "character" }, 
    { word: "радостный", translation: "happy" }, 
    { word: "умный", translation: "smart" }, 
    { word: "сбитый с толку", translation: "confused" }, 
    { word: "креативный", translation: "creative" }, 
    { word: "жестокий", translation: "cruel" }, 
    { word: "любопытный", translation: "curious" }, 
    { word: "легкий на подъем", translation: "energetic" }, 
    { word: "эмоциональный", translation: "emotional" }, 
    { word: "взволнованный", translation: "excited" }, 
    { word: "честный", translation: "honest" }, 
    { word: "дружелюбный", translation: "friendly" }, 
    { word: "щедрый", translation: "generous" }, 
    { word: "гениальный", translation: "genius" }, 
    { word: "мягкий", translation: "gentle" }, 
    { word: "довольный", translation: "satisfied" }, 
    { word: "жадный", translation: "greedy" }, 
    { word: "счастливый", translation: "happy" }, 
    { word: "трудолюбивый", translation: "hardworking" }, 
    { word: "честный", translation: "honest" }, 
    { word: "умный", translation: "smart" }, 
    { word: "ревнивый", translation: "jealous" }, 
    { word: "добрый", translation: "kind" }, 
    { word: "ленивый", translation: "lazy" }, 
    { word: "верный", translation: "loyal" },
    { word: "удачливый", translation: "lucky" }, 
    { word: "хмурый", translation: "moody" }, 
    { word: "нервный", translation: "nervous" }, 
    { word: "открытый", translation: "open" }, 
    { word: "оптимистичный", translation: "optimistic" }, 
    { word: "терпеливый", translation: "patient" }, 
    { word: "гордый", translation: "proud" }, 
    { word: "тихий", translation: "quiet" }, 
    { word: "надежный", translation: "reliable" }, 
    { word: "романтичный", translation: "romantic" }, 
    { word: "грубый", translation: "rude" }, 
    { word: "грустный", translation: "sad" }, 
    { word: "стеснительный", translation: "shy" }, 
    { word: "чувствительный", translation: "sensitive" }, 
    { word: "серьезный", translation: "serious" }, 
    { word: "глупый", translation: "silly" }, 
    { word: "талантливый", translation: "talented" }, 
    { word: "жесткий", translation: "tough" }, 
    { word: "расстроенный", translation: "upset" },
    { word: "мудрый", translation: "wise" },
    { word: "остроумный", translation: "witty" },
    { word: "вести себя", translation: "behave" },
    { word: "рассказывать", translation: "tell" },
    { word: "стараться", translation: "try" },
    { word: "усыновление", translation: "adoption" },
    { word: "тетя", translation: "aunt" },
    { word: "парень", translation: "boyfriend" },
    { word: "невеста", translation: "bride" },
    { word: "брат", translation: "brother" },
    { word: "шурин", translation: "brother-in-law" },
    { word: "двоюродный брат или сестра", translation: "cousin" },
    { word: "дочь", translation: "daughter" },
    { word: "сноха", translation: "daughter-in-law" },
    { word: "развод", translation: "divorce" },
    { word: "помолвка", translation: "engagement" },
    { word: "бывший муж", translation: "ex-husband" }, 
    { word: "бывшая жена", translation: "ex-wife" },
    { word: "семья", translation: "family" }, 
    { word: "отец", translation: "father" },
    { word: "приемная семья", translation: "foster family" },
    { word: "друг", translation: "friend" },
    { word: "девушка", translation: "girlfriend" },
    { word: "крестный отец", translation: "godfather" },
    { word: "крестная мать", translation: "godmother" },
    { word: "внуки", translation: "grandchildren" },
    { word: "внучка", translation: "granddaughter" },
    { word: "дедушка", translation: "grandfather" },
    { word: "бабушка", translation: "grandmother" },
    { word: "бабушка и дедушка", translation: "grandparents" },
    { word: "внук", translation: "grandson" },
    { word: "брат со стороны отца или матери", translation: "half-brother" },
    { word: "сестра со стороны отца или матери", translation: "half-sister" },
    { word: "муж", translation: "husband" },
    { word: "любовник", translation: "lover" },
    { word: "брак", translation: "marriage" },
    { word: "мать", translation: "mother" },
    { word: "теща", translation: "mother-in-law" },
    { word: "племянник", translation: "nephew" },
    { word: "племянница", translation: "niece" },
    { word: "родители", translation: "parents" },
    { word: "родственник", translation: "relative" },
    { word: "сестра", translation: "sister" },
    { word: "сын", translation: "son" },
    { word: "сводный брат", translation: "stepbrother" },
    { word: "отчим", translation: "stepfather" },
    { word: "мачеха", translation: "stepmother" },
    { word: "сводная сестра", translation: "stepsister" },
    { word: "близнецы", translation: "twins" },
    { word: "дядя", translation: "uncle" },
    { word: "свадьба", translation: "wedding" },
    { word: "вдова", translation: "widow" },
    { word: "вдовец", translation: "widower" },
    { word: "жена", translation: "wife" },
    { word: "заботиться", translation: "care" },
    { word: "любить", translation: "love" },
    { word: "скучать", translation: "miss" },
    { word: "поддерживать", translation: "support" },
    { word: "ремень", translation: "belt" },
    { word: "блузка", translation: "blouse" },
    { word: "ботинки", translation: "boots" },
    { word: "браслет", translation: "bracelet" },
    { word: "кепка", translation: "cap" },
    { word: "цепочка", translation: "chain" },
    { word: "плащ", translation: "coat" },
    { word: "одежда", translation: "clothes" },
    { word: "пальто", translation: "coat" },
    { word: "платье", translation: "dress" },
    { word: "серьги", translation: "earrings" },
    { word: "официальная одежда", translation: "formal wear" },
    { word: "шляпа", translation: "hat" },
    { word: "сапоги", translation: "boots" },
    { word: "высокие каблуки", translation: "high heels" },
    { word: "худи", translation: "hoodie" },
    { word: "пиджак", translation: "jacket" },
    { word: "джинсы", translation: "jeans" },
    { word: "ожерелье", translation: "necklace" },
    { word: "карман", translation: "pocket" },
    { word: "пижама", translation: "pajamas" },
    { word: "плащ-дождевик", translation: "raincoat" },
    { word: "кольцо", translation: "ring" },
    { word: "рубашка", translation: "shirt" },
    { word: "туфли", translation: "shoes" },
    { word: "шорты", translation: "shorts" },
    { word: "юбка", translation: "skirt" },
    { word: "тапочки", translation: "slippers" },
    { word: "носки", translation: "socks" },
    { word: "спортивный костюм", translation: "tracksuit" },
    { word: "костюм", translation: "suit" },
    { word: "свитер", translation: "sweater" },
    { word: "купальный костюм", translation: "swimsuit" },
    { word: "кроссовки", translation: "sneakers" },
    { word: "футболка", translation: "t-shirt" },
    { word: "зонт", translation: "umbrella" },
    { word: "нижнее белье", translation: "underwear" },
    { word: "униформа", translation: "uniform" },
    { word: "застежка-молния", translation: "zipper" },
    { word: "квартира", translation: "apartment" },
    { word: "подвал", translation: "basement" },
    { word: "потолок", translation: "ceiling" },
    { word: "пол", translation: "floor" },
    { word: "дом", translation: "house" },
    { word: "сосед", translation: "neighbor" },
    { word: "крыша", translation: "roof" },
    { word: "лестница", translation: "stairs" },
    { word: "стена", translation: "wall" },
    { word: "двор", translation: "yard" },
    { word: "кресло", translation: "armchair" },
    { word: "книжный шкаф", translation: "bookshelf" },
    { word: "ковер", translation: "carpet" },
    { word: "кофейный столик", translation: "coffee table" },
    { word: "компьютер", translation: "computer" },
    { word: "шторы", translation: "curtains" },
    { word: "рабочий стол", translation: "desk" },
    { word: "лампа", translation: "lamp" },
    { word: "ноутбук", translation: "laptop" },
    { word: "плохой", translation: "bad" },
    { word: "большой", translation: "big" },
    { word: "круг", translation: "circle" },
    { word: "прохладный", translation: "cool" },
    { word: "далекий", translation: "distant" },
    { word: "быстрый", translation: "fast" },
    { word: "пушистый", translation: "fluffy" },
    { word: "хороший", translation: "good" },
    { word: "жесткий", translation: "hard" },
    { word: "тяжелый", translation: "heavy" },
    { word: "высокий", translation: "high" },
    { word: "горячий", translation: "hot" },
    { word: "крупный", translation: "large" },
    { word: "длина", translation: "length" },
    { word: "легкий", translation: "light" },
    { word: "линия", translation: "line" },
    { word: "длинный", translation: "long" },
    { word: "громкий", translation: "loud" },
    { word: "низкий", translation: "low" },
    { word: "новый", translation: "new" },
    { word: "старый", translation: "old" },
    { word: "быстрый", translation: "quick" },
    { word: "круглый", translation: "round" },
    { word: "форма", translation: "shape" },
    { word: "острый", translation: "sharp" },
    { word: "короткий", translation: "short" },
    { word: "размер", translation: "size" },
    { word: "медленный", translation: "slow" },
    { word: "маленький", translation: "small" },
    { word: "гладкий", translation: "smooth" },
    { word: "мягкий", translation: "soft" },
    { word: "скорость", translation: "speed" },
    { word: "теплый", translation: "warm" },
    { word: "вес", translation: "weight" },
    { word: "день", translation: "day" },
    { word: "век", translation: "century" },
    { word: "дата", translation: "date" },
    { word: "день", translation: "day" },
    { word: "десятилетие", translation: "decade" },
    { word: "вечер", translation: "evening" },
    { word: "час", translation: "hour" },
    { word: "полночь", translation: "midnight" },
    { word: "минута", translation: "minute" },
    { word: "месяц", translation: "month" },
    { word: "утро", translation: "morning" },
    { word: "ночь", translation: "night" },
    { word: "секунда", translation: "second" },
    { word: "время", translation: "time" },
    { word: "неделя", translation: "week" },
    { word: "будни", translation: "weekdays" },
    { word: "выходные", translation: "weekend" },
    { word: "год", translation: "year" },
    { word: "зима", translation: "winter" },
    { word: "весна", translation: "spring" },
    { word: "лето", translation: "summer" },
    { word: "осень", translation: "autumn" },
    { word: "январь", translation: "January" },
    { word: "февраль", translation: "February" },
    { word: "март", translation: "March" },
    { word: "апрель", translation: "April" },
    { word: "май", translation: "May" },
    { word: "июнь", translation: "June" },
    { word: "июль", translation: "July" },
    { word: "август", translation: "August" },
    { word: "сентябрь", translation: "September" },
    { word: "октябрь", translation: "October" },
    { word: "ноябрь", translation: "November" },
    { word: "декабрь", translation: "December" },
    { word: "воздух", translation: "air" },
    { word: "метель", translation: "blizzard" },
    { word: "прохладный", translation: "cool" },
    { word: "чистый", translation: "clean" },
    { word: "облако", translation: "cloud" },
    { word: "облачный", translation: "cloudy" },
    { word: "холод", translation: "cold" },
    { word: "туман", translation: "fog" },
    { word: "туманный", translation: "foggy" },
    { word: "морозный", translation: "freezing" },
    { word: "жаркий", translation: "hot" },
    { word: "лед", translation: "ice" },
    { word: "ледяной", translation: "icy" },
    { word: "молния", translation: "lightning" },
    { word: "луна", translation: "moon" },
    { word: "грязь", translation: "mud" },
    { word: "лужа", translation: "puddle" },
    { word: "дождь", translation: "rain" },
    { word: "радуга", translation: "rainbow" },
    { word: "дождливый", translation: "rainy" },
    { word: "небо", translation: "sky" },
    { word: "снег", translation: "snow" },
    { word: "снегопад", translation: "snowfall" },
    { word: "снежинка", translation: "snowflake" },
    { word: "снежный", translation: "snowy" },
    { word: "звезда", translation: "star" },
    { word: "звездный", translation: "starry" },
    { word: "солнце", translation: "sun" },
    { word: "солнечный свет", translation: "sunlight" },
    { word: "солнечный", translation: "sunny" },
    { word: "рассвет", translation: "sunrise" },
    { word: "закат", translation: "sunset" },
    { word: "гром", translation: "thunder" },
    { word: "гроза", translation: "storm" },
    { word: "погода", translation: "weather" },
    { word: "ветер", translation: "wind" },
    { word: "ветреный", translation: "windy" },
    { word: "стучать", translation: "knock" },
    { word: "дуть", translation: "blow" },
    { word: "покрывать", translation: "cover" },
    { word: "темнеть", translation: "darken" },
    { word: "капать", translation: "drip" },
    { word: "падать", translation: "fall" },
    { word: "светлеть", translation: "brighten" },
    { word: "таять", translation: "melt" },
    { word: "пещера", translation: "cave" },
    { word: "скала", translation: "rock" },
    { word: "пустыня", translation: "desert" },
    { word: "пыль", translation: "dust" },
    { word: "поле", translation: "field" },
    { word: "лес", translation: "forest" },
    { word: "земля", translation: "earth" },
    { word: "холм", translation: "hill" },
    { word: "остров", translation: "island" },
    { word: "джунгли", translation: "jungle" },
    { word: "озеро", translation: "lake" },
    { word: "гора", translation: "mountain" }
  ];
      // Генерирует заданное количество рандомных слов из массива
      function generateRandomWords(numWords) {
        const randomWords = [];
        for (let i = 0; i < numWords; i++) {
          const randomIndex = Math.floor(Math.random() * words.length);
          randomWords.push(words[randomIndex]);
        }
        return randomWords;
      }

      // Создает инпут для ввода предложения с каждым словом
      function createWordInputs() {
        const wordsContainer = document.getElementById("words-container");
        wordsContainer.innerHTML = "";
        const randomWords = generateRandomWords(15);

        randomWords.forEach(wordObj => {
          const wordInputDiv = document.createElement("div");
          wordInputDiv.style.marginBottom = "10px";

          const wordSpan = document.createElement("span");
          wordSpan.textContent = `Слово: ${wordObj.translation}`;
          wordInputDiv.appendChild(wordSpan);
          // wordSpan.style.minWidth = '200px';


          const wordInput = document.createElement("input");
          wordInput.type = "text";
          wordInput.dataset.word = wordObj.word;
          wordInput.placeholder = `Введите перевод "${wordObj.translation}"`;
          wordInput.addEventListener("change", checkWordInput);
          wordInputDiv.appendChild(wordInput);

          wordsContainer.appendChild(wordInputDiv);
          const wordSpanafter = document.createElement("div");
          wordSpanafter.classList.add("after-word-span"); 
          wordInputDiv.appendChild(wordSpanafter);
        });
      }

      // Проверяет, правильно ли введено слово
      function checkWordInput(event) {
        const input = event.target;
        const word = input.dataset.word;
    
        const correctInput = input.parentElement.querySelector(".after-word-span");
        correctInput.textContent = `Верно: ${word}`;
    
        if (input.value.toLowerCase().includes(word)) {
          input.style.backgroundColor = "lightgreen";
          input.setAttribute("readonly", true);
          correctInput.textContent = ` `;

        } 
        else {
          input.style.backgroundColor = "pink";
        }
      }
